producer:
  bootstrap: localhost:9092
  brokers: localhost:9092
  producttopic: transaction
  partitionCount: 1
  acks: all
  retries: 3
  minPoolSize: 80
  maxPoolSize: 120
  filePath: /Users/raghugupta/Documents/ApacheKafka_Case_Studies/Module_8.1_transactions.csv